eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: like-service
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      database: like_db
      port: 27017
server:
  port: 3020
